name: letsconnectnewui
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  intl_phone_number_input: ^0.7.1
  grouped_buttons_ns: ^1.0.0
  multi_select_flutter: ^4.1.2
  
  percent_indicator: ^4.2.2
  flutter_swiper: ^1.1.6
  scrollable_list_tabview: ^0.1.6
  swipe_cards: ^1.0.0
  scroll_snap_list: ^0.9.1
  lottie: ^1.4.2
  flutter_screenutil: ^5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  
  uses-material-design: true
 
  assets:
    - assets/onboarding/
    - assets/loginpage/
    - assets/createaccount/
    - assets/logo.png
    - assets/doodlee.png
    - assets/notifications/
    - assets/profile/
    - assets/homepage/
  
   
   
    
  
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 700
      



  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
